### ISSUE TITLE
Air-conditioner real temperature value

### ISSUE THREAD

**Issue by acc-ua** [lprhodes/homebridge-broadlink-rm#202] opened 2017-10-22 22:45 UTC
Is there any way to add configuration for external temperature sensor for Air-conditioner ?
I have a external temperature sensor (xiaomi) that is available in HomeKit, and it will be useful if air-conditioner accessory can use it's real temperature value.

**Comment by alesf** [comment] 2017-10-24 10:44
I also have this feature request. Maybe the easiest way would be to pool for temperature from local file or url.

**Comment by alesf** [comment] 2017-10-24 10:47
I see this is dupe of https://github.com/lprhodes/homebridge-broadlink-rm/issues/164

**Closed** 2018-02-08 09:06 UTC
Labels: duplicate
