### ISSUE TITLE
Sync devices power status (on or off) between remote and homekit

### ISSUE THREAD

**Issue by felipesalomao** [lprhodes/homebridge-broadlink-rm#212] opened 2017-12-01 06:25 UTC
I am able to turn on or turn off devices like tv.. But main problem is: If i Turn On tv using homekit, then after turnoff Tv using my tv remote, homebridge dont know that i turned off tv.. So if i ask to turn on tv, it says that its already on and does not send power command..

I thinked in Perfect Solution for this.. But i dont know if it exist or could be developed..
If IR sensor receiver from RM3 or even ir sensor attached at raspeberry pi could detect new IR signals.. When it detect ir from remote, it change homekit status of device.. This way, never device would be out of sync because was used device ir remote or homekit.. 
This is one solution, another is for tv for example just send ping to tv address, if it answer, its on, if its does not answer, its off.. 

Who could develop this?! Would be awesome!

**Comment by lprhodes** [comment] 2018-02-08 09:12
I'll be implementing the ping solution shortly. Dupe of #154

**Closed by lprhodes** 2018-02-08 09:12 UTC
