### ISSUE TITLE
Add frequency-scan variation of learning RF codes 

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#29] opened 2017-03-31 09:51 UTC
First of all I have to say, what you did is quite impressive... I have few broadlink devices and the only way I was able to control them eventually is via UDP packets.
To do that, I had to learn the the codes on the app and the capture the packets in Wireshark connected to my phone. so what you did here really makes it easy to use in HomeKit!

another thing is that I wanted to know if it will be possible in the future to also learn some RF codes, since I also have the broadlink RM Pro, I'm using a lot of radio frequency devices, recording those hex codes would be great!

I'm also using this device to control blinds, locks & garage door, so have the ability to choose any type of accessory would really ramp this plugin up, something like [emilletfr did in homebridge-httpeverything](https://github.com/emilletfr/homebridge-httpeverything).

one last thing, if you'll be able to crack that S1C device (security system) and his sensors you will be my king! I'm willing to pay for that too :)

**Comment by lprhodes** [comment] 2017-04-01 04:09
Hey - I'll check out RF learning next week some time. 

How are you planning on learning garage door RF they generally have rolling codes for security purposes which prevent you from using these kinds of devices for them.

Http everything's looks to only support very basic on/off characteristics for each device type whereas I'm looking to implement deeper support for each (similar to how I have with the thermostat) which will take longer and priority will be based on requests from people like yourself.

I don't have an S1C device to be able to test anything on it sorry! I personally use the new devices from http://homekit.fibaro.com for that kind of thing.

**Comment by duyleekun** [comment] 2017-04-04 04:28
Using https://play.google.com/store/apps/details?id=us.originally.rm_trial&hl=en
You can get control codes from the http bridge and use it with @lprhodes plugin. I've sucessfully using my RM Pro with 315mhz and Broadlink TC2 with this plugin untouched

![img_2411](https://cloud.githubusercontent.com/assets/1965712/24641410/b259b20c-1929-11e7-9f10-6ff9a79fbe06.PNG)

**Comment by PianSom** [comment] 2017-04-10 11:03
I can confirm that the current code will operate (though not learn) 433MHz switches also. I have not tested this with rolling codes. Not least because I have not managed to get my RM3 to use rolling codes yet.

I obtained the hex code from the (free, and supposedly more secure) Android app RM Bridge, using it with http://rm-bridge.fun2code.de/rm_manage/code_learning.html

**Comment by lprhodes** [comment] 2017-04-18 08:42
New release but this didn't make it sorry - I'll try tackle this tomorrow

**Comment by webpablo** [comment] 2017-04-20 16:12
Didn't this work in an earlier release? perhaps by accident? I have two hex values that I have been using for my shade project and I know for certain I didn't get them any other way than through the learn-IR on an earlier version. ¯\_(ツ)_/¯. Either way. great work and I look forward to RF learning so I can add my stop button to your awesome new window covering changes.

**Comment by SeanJohn888** [comment] 2017-04-20 18:23
The rf hex learn about the ir switch from the hub works without problems with me.

Not with you?

**Comment by lprhodes** [comment] 2017-04-20 20:48
The RM 3 (RM2+) requires an additional RF scan before it can learn a code so I would guess you both have RM2's @webpablo and @SeanJohn888? The RM2 uses the exact same method for learning RF as it does for learning IR.

**Comment by lprhodes** [comment] 2017-04-20 20:49
No-one seems to have figured out how to perform the RF scan yet for RM3 (RM2+). I'm making progress though.

**Comment by SeanJohn888** [comment] 2017-04-21 03:13
Ich habe bei mir gerade nachgesehen, ich habe einen (Rm 3) 
![img_5847](https://cloud.githubusercontent.com/assets/27686185/25261129/0387a218-2651-11e7-840b-4cbced454b9b.jpg)

Das hier ist der unterschied:

![img_1454](https://cloud.githubusercontent.com/assets/27686185/25261150/203a3de4-2651-11e7-8ad1-51c1a5e169ad.PNG)

**Comment by lprhodes** [comment] 2017-04-21 05:37
I guess it's just certain types of RF codes in that case - possibly based on the frequency

**Comment by SeanJohn888** [comment] 2017-04-21 05:54
You're right, I just tried to learn my sunblade radio control. That will not do.

[Broadlink RM] Learn RF (RF learning not supported for device at undefined)

The function is still inserted by you. Have I understood that correctly?

**Comment by SeanJohn888** [comment] 2017-04-21 05:54
Das lernen über die e-control app hat funktioniert.

**Comment by lprhodes** [comment] 2017-04-21 08:59
@SeanJohn888  > [Broadlink RM] Learn RF (RF learning not supported for device at undefined)

That was a separate issue - I'd released some code that wasn't ready by accident. Can you please update to 2.0.0 and try again.

**Comment by PianSom** [comment] 2017-04-21 09:08
@SeanJohn888 Have you managed to get your RM3 to learn and operate rolling codes using any software? I have had no success at all, and am not even certain that there is hardware support

**Comment by lprhodes** [comment] 2017-04-21 09:09
I wouldn't expect hardware support - there's usually some sort of encryption key so people can't just steal your garage door codes...

**Comment by PianSom** [comment] 2017-04-21 09:12
Really? I wonder why the RM2 won't do it then? (See [here](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjVran4mbXTAhUKblAKHWjmDckQFggqMAE&url=http%3A%2F%2Fwww.broadlink.com.cn%2Fen%2Fdownloads%2Fppt-corp-intro.pdf&usg=AFQjCNFmAdNxkaTz0Bf8YgNdXDg6uUHr0Q) for hint that only RM3 supports rolling codes)

**Comment by lprhodes** [comment] 2017-04-21 09:16
I would guess that some devices don’t use encryption but generally speaking they do - you may be able to learn from the garage door opener pairing function (usually on the garage door opener in your garage) but from the hours I spent trying to get things to work I had no luck so put it down to the encryption.

**Comment by SeanJohn888** [comment] 2017-04-21 09:23
RF learning works with the new version 👍

**Comment by PianSom** [comment] 2017-04-21 09:27
I guess - though I don't really see why if you have a garage door opener which uses a rolling code algorithm why it should be that the RM3 can (in principle) learn/replay but the RM2 cannot, if it's not hardware related. 

BTW you said above "No-one seems to have figured out how to perform the RF scan yet for RM3 (RM2+)." - I'm not sure that's quite true. I use [this](http://rm-bridge.fun2code.de) which seems quite happy to do 433MHz learning/operating with my RM3.

**Comment by lprhodes** [comment] 2017-04-21 09:33
Yeah I’ve recompiled their android bridge app and found that it uses a closed library developed by broadlink so it’s not really worked it out in a usable way - it’s just using exactly what their own app uses.

**Comment by lprhodes** [comment] 2017-04-26 06:24
Hey all - for those of you who still have RF devices that they can't learn...

I've just pushed out some test code for scanning RF - check out the release notes:

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.0.11

I think I have the first part (the scanning) working but I'm unsure if the next part just uses the normal learn code (which is what it uses in the test) or whether it's something different. So it'd be useful for you to test it when you can.

Can you make sure you can learn and use whichever RF device you're testing with from the official app too so we know that's not the issue.

**Comment by SeanJohn888** [comment] 2017-04-26 18:55
I have tested the new RF function. I have inserted the new learn switch in the config and re-installed broadlinkjs. The old IR learn switch has disappeared. With the new switch, I can not learn IR commands anymore?

**Comment by lprhodes** [comment] 2017-04-27 02:12
@SeanJohn888  Adding the "scanRF" setting changes the type of learning the "learn-code" switch does.

When you add a "learn-code" accessory yourself the plugin doesn't add one automatically.

You have two options:

1. Remove the "learn-code" switch you just added
2. Add another "learn-code" switch and call it "Learn Code" but don't add a "scanRF" config value.

I would recommend 2. so that you can continue the alpha testing of the Scan RF switch.

I'll be working further on Scan RF over the weekend.

**Comment by jeylites** [comment] 2017-04-27 02:28
Is this compatible with Broadlink TC2 and 433mhz RF switches? 

I have a buch of RF, IR codes on E-control app and I was wondering if if there's a way to send codes to WLAN share?

**Comment by lprhodes** [comment] 2017-04-27 02:29
You'd have to try and see

**Comment by jeylites** [comment] 2017-04-27 02:31
Will do.

**Comment by jeylites** [comment] 2017-04-27 03:09
@lprhodes Ran the install and followed by an error. Is this normal?

pi@raspberrypi:~ $ npm install -g homebridge-broadlink-rm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ homebridge-broadlink-rm@2.0.15 
  ├─┬ broadlinkjs@0.1.0  (git+https://github.com/lprhodes/broadlinkjs.git#4a90e87230c024cde83f506ad12d606d41ac0d58)
  │ └── @types/node@7.0.14 
  ├─┬ node-persist@2.0.11 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ └── q@1.1.2 
  └── semver@5.3.0 

npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-broadlink-rm"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
pi@raspberrypi:~ $

**Comment by lprhodes** [comment] 2017-04-27 03:11
@jeylites Please create new issues when they're different to the issue being discussed

**Comment by mrblack7** [comment] 2017-04-27 05:50
Would this enhancement cover 433 rolling codes?
I have some motorised blinds that I can learn through the Broadlink app using 'Sweap Frequency' but if I try and capture them through this plugin, the hex code is different every time.

**Comment by eviewei** [comment] 2017-04-27 06:03
[2017-4-27 13:52:21] [Broadlink RM] Scan RF (found frequency - now press the RF button multiple times with a pause between them)
[2017-4-27 13:52:21] [Broadlink RM] Learn Code (ready)
[2017-4-27 13:52:31] [Broadlink RM] Learn Code (stopped - 10s timeout)
It receives no RF,why?

**Comment by lprhodes** [comment] 2017-04-27 06:22
@mrblack7 Yes it should work the same as the broadlink app once it's fully working

**Comment by mrblack7** [comment] 2017-04-27 06:28
Great. Would be happy to help.

I am using an RM 3 Pro (newest version) with Acmeda motorised blinds (from what I understand, these are rebadged Somfy motors)

I've just added the ScanRF accessory and attempted to learn the code, but it still seems to be picking up a different one every time.

`Apr 27 16:22:38 raspberrypi homebridge[703]: [4/27/2017, 4:22:38 PM] [Broadlink RM] Learn Code (ready)
Apr 27 16:22:39 raspberrypi homebridge[703]: [4/27/2017, 4:22:39 PM] [Broadlink RM] Learn Code (learned hex code: b200b2000c190e191a0d1a00012296350d191a0d1a0c1a0d180c0d170d18190e190d0d1a0d190d190d170d181a0c1a0d1a0d0d191a0d190c180c190c0c191a0d0d1a0d191a0d190c0c18190b1a0d0d1b0d190d191b0c190c0c180c181a0c1b00012097350d1a180c180c190b190c0c180c18190b190c0c180d170d180c180d18190c190c180c0c18190c180c180c190b0d18180c0c190c18180c190b0d18180c180c0d170e180d18180c180c0d170d18180c190005dc000000000000)
Apr 27 16:22:39 raspberrypi homebridge[703]: [4/27/2017, 4:22:39 PM] [Broadlink RM] Learn Code (complete)
Apr 27 16:22:43 raspberrypi homebridge[703]: [4/27/2017, 4:22:43 PM] [Broadlink RM] Scan RF (scanning - keep holding the button that sends the RF frequency)
Apr 27 16:22:47 raspberrypi homebridge[703]: [4/27/2017, 4:22:47 PM] [Broadlink RM] Scan RF (found frequency - now press the RF button multiple times with a pause between them)
Apr 27 16:22:47 raspberrypi homebridge[703]: [4/27/2017, 4:22:47 PM] [Broadlink RM] Learn Code (ready)
Apr 27 16:22:47 raspberrypi homebridge[703]: [4/27/2017, 4:22:47 PM] Online: Towel Heater [8006FA5C92CA7DB5E9DDF07CDC3BD20418237BE0]
Apr 27 16:22:52 raspberrypi homebridge[703]: [4/27/2017, 4:22:52 PM] [Broadlink RM] Learn Code (learned hex code: b200da001b0c0d1a1a0d1a0c1a0c180c0d17190d0d1a0e191a0d1a0d0c18190b190c0c1a0d1a0d191a0d1a0c0d180c18190b1a0001259a320d18180c1b0c1a0d190d0d190e181a0c180c0d180e1a0d190d190e1a180c180c190b0d1a190d1a0d1a0c1a0d0d17190c0d180e191a0d1a0d0c1a1a0c190b0d170d180d1a1a0d1a0c0d190e18190b1900012194330c18180c190b190b190c0c180c19190c190b0d180c180d170d170d18190b190c180c0c18190b190c180c190b0d18180c0d190c18190b190c0c18180c180c0d180c180d18180c180c0c190c18180c190005dc0000000000000000000000000000)
Apr 27 16:22:52 raspberrypi homebridge[703]: [4/27/2017, 4:22:52 PM] [Broadlink RM] Learn Code (complete)
Apr 27 16:23:07 raspberrypi homebridge[703]: [4/27/2017, 4:23:07 PM] [Broadlink RM] Scan RF (scanning - keep holding the button that sends the RF frequency)
Apr 27 16:23:12 raspberrypi homebridge[703]: [4/27/2017, 4:23:12 PM] [Broadlink RM] Scan RF (found frequency - now press the RF button multiple times with a pause between them)
Apr 27 16:23:12 raspberrypi homebridge[703]: [4/27/2017, 4:23:12 PM] [Broadlink RM] Learn Code (ready)
Apr 27 16:23:17 raspberrypi homebridge[703]: [4/27/2017, 4:23:17 PM] Online: Towel Heater [8006FA5C92CA7DB5E9DDF07CDC3BD20418237BE0]
Apr 27 16:23:17 raspberrypi homebridge[703]: [4/27/2017, 4:23:17 PM] [Broadlink RM] Learn Code (learned hex code: b20184030d180c180d18180c180c190c0c18190b190b190c180c0d18180c0d170e18180c190b0d18180c190b0d180c180d17190b190b190c180d0c180c00012991350d1a1a0d1a0c180c190c0c180d191b0c1c0c0e190d180d180c180c191a0d1a0c1a0d0e19190c190c180c190d0c1a1a0c0e190d1c180c180c0c181a0d1a0c0e190d190e19180c190c180c1a0c0d1a0e0005529f340d18180c180d1a0d1a0d0d190d1a190c180c0c190c190d1a0d1a0d1a1a0d190c180c0c181a0d1a0c1a0d1a0d0d19180c0c190c181a0d1a0d0d191a0c1a0c0c1a0c180c191b0c1a0c0e190e19190c1900012397350d1a180c180d180c1a0c0e190d191a0d1b0c0c180c180d180d190d1b1a0d1a0d190c0d17190c180d1a0d190d0d1a1a0d0d180c18190b1a0c0d1a1a0c1a0e0d1a0c180c19180c180c0c190c18190c1b00012092320c18190b190c180c190b0d170d18180c190c0c180d180c180c180c19190c180c190b0d18180c190c180c180c0d18180c0c180d17190c180c0d17190c180c0d190c180c18190b190c0c180d17190c1800057f91320c18190b1a0c180c190b0d170d18190b190c0c180c190c180c180c18190c180c190b0d18180c190b1a0c180c0d18180c0c190c18180c180c0d17190c180c0d180c180c18190b190c180c190b0e180c00012890320d18180c180c1a0c180c0c180d17190c180c0d170d180c180c190c18190b190b190c0c18190b190c180c1a0c0c18190b0d180c18180c190c0c18190b190c0c180d180c18180c180c190c180c0c180d00012990320c18180c190b190c1a0c0c180c18190b190c0c180d170d180c180c18190c180d180c0c18190b190c180c180c0c19190c0d180c18180c180c0d18180c190b0d180c180d17190b190c180c190c0c180c00012990320d18180c190b190c180c0c190d18180c180d0c180c180d170d180c18190b190c190b0d18180c180c180c190c0c18190d0c180d17190b190c0d17190c180c0c180d170d18190b190b190b190c0d170d00012990320c18190c180c180c190b0d180c181a0c180c0d180c180c180d180c18180c190c180c0c18190b190c180c190c0c18180c0d180d18190c180c0d17180c190c0c180d170d18180c180c190c180c0c180d00012990320c18190b190c180c180d0c180c18190b1a0c0c180d180c180c180d17190c180c190b0d18190b190b190c180c0d17190c0c180d18190c180c0d18180c180c0d180c180d17190b190c180c190c0c180c0005dc00000000)
Apr 27 16:23:17 raspberrypi homebridge[703]: [4/27/2017, 4:23:17 PM] [Broadlink RM] Learn Code (complete)
Apr 27 16:23:22 raspberrypi homebridge[703]: [4/27/2017, 4:23:22 PM] [Broadlink RM] Scan RF (scanning - keep holding the button that sends the RF frequency)
Apr 27 16:23:25 raspberrypi homebridge[703]: [4/27/2017, 4:23:25 PM] [Broadlink RM] Scan RF (found frequency - now press the RF button multiple times with a pause between them)
Apr 27 16:23:25 raspberrypi homebridge[703]: [4/27/2017, 4:23:25 PM] [Broadlink RM] Learn Code (ready)
Apr 27 16:23:28 raspberrypi homebridge[703]: [4/27/2017, 4:23:28 PM] [Broadlink RM] Learn Code (learned hex code: b200f6010c18180c1a0c180c190c0c180c18180d180c0c180d170d180c180c18190c180c190b0d18180c190c190c180c0d18180c0c180d18180c180c0d18180c180c0c190c180c18190c180c180c190b0e180c00012890320d18180c180c1a0c180c0c180c19180c190b0d180c180c190c180c18180c190c180c0d17190c180c190b1a0c0d17190c0c180c18190c180c0c18190c180c0d170d180c18190b190c180c180c0c190c00012990320d18180c180c180d190c0c190c18180c190b0d180c180d170d170d18180c190c180c0d18180c180c190b190c0c19180d0c180d17190c180c0c18190c180c0c180d180c18180c190c180c180c0d180c00012990320d17190c180c180c190c0c190d18180c190c0c180c180c180d170d18190b190c180c0d18180c180c180c190c0c18180e0c180d17190b190c0c18190c180c0c180d180c18190b190b190c180c0d170d00012990320d17190c180c190b190c0c180c181a0c180c0d180c180c180d180c18190b190b190c0c18190b190c180c190c0c18180d0c180d18190b190c0c18190b190c0c180c190c18180c180c190c180c0c180d00012990320c18190c180c180d180c0c180c18190c1a0b0d180c180d170d170d18180c180d180c0d17190c180c180c190c0c18180c0d180c181a0b190c0c18190b190c0c180d170d18180c190c180c180c0d180c0005dc0c18)
Apr 27 16:23:28 raspberrypi homebridge[703]: [4/27/2017, 4:23:28 PM] [Broadlink RM] Learn Code (complete)
`

**Comment by lprhodes** [comment] 2017-04-27 06:46
Yeah the Scan RF one seems is work in progress - the first part seems to be working as it should be need to guess the right codes for the next party. At the moment the second part is just using the same functionality as a normal learn.

**Comment by eviewei** [comment] 2017-04-27 06:51
315 learn ok(projection screen),light switch(may313~317)didn't learn.In broadlink App everyone worked ok.

**Comment by lprhodes** [comment] 2017-04-27 16:03
Eureka ;)

**Comment by lprhodes** [comment] 2017-04-27 16:53
I think I've got it - please test in 2.1.1 (check out the [release notes](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.1.1))

**Comment by lprhodes** [comment] 2017-04-27 16:55
...make sure you test with something you know the broadlink app can learn please - so I can know that the issue isn't with the device you want to learn. Thanks!

**Comment by mrblack7** [comment] 2017-04-28 01:51
Eureka indeed!

I have tried this and it seems to work for my motorised blinds! Learnt the code and able to open and close (haven't tried STOP command yet)
With my RF switches though, seems to be hit and miss. The Broadlink app work without issue for this. Normal Lean Code will pick up the rolling codes.

**Comment by lprhodes** [comment] 2017-04-28 02:07
Thanks for testing @mrblack7!

>  The Broadlink app works without issue for this
Do you press "Learn" or "Sweep Frequency" for this to work?

The "Learn Code" accessory (without "scanRF" in the config) will work like the "Learn" option and the "Scan RF" (with scanRF config set to true) works like the "Seep Frequency" option.

**Comment by lprhodes** [comment] 2017-04-28 02:27
I've just released 2.2.1 which adds this as a default accessory - you can now remove the accessory from your config.

**Comment by lprhodes** [comment] 2017-04-28 02:51
Closing - please create new issues if they come up

**Closed by lprhodes** 2017-04-28 02:51 UTC
Labels: enhancement

**Comment by lapo76** [comment] 2017-07-14 11:26
Sory I'm not so expert, but where do you load the iprhodes' plugin? Do you use a raspberry, please? Sorry fo the question.

**Comment by hpascual** [comment] 2017-12-10 18:40
Hi, I just installed your plugin, I think your latest version (BTW, how do I check which version do I have installed?), and I am getting different HEX Codes for mi RF commands. Any idea?

**Comment by staticnz** [comment] 2018-03-22 10:30
@mrblack7 I have acmeda blinds as well, but I can't get it to learn any codes, it just times out. How did you manage it?

**Comment by lprhodes** [comment] 2018-03-22 11:57
Hey @lapo76  @hpascual  @staticnz 

Please create new issues if you still need help.

**Comment by boogieman5** [comment] 2018-03-31 08:47
Good day! Here you are talking about Broadlink RM and TC2. Send commands to TC2 via Broadlink RM. I'm interested in the management of TC2 in the absence of Broadlink RM. What is the learning protocol for TC2?
Доброго дня! Тут вы говорите о Broadlink RM  и TC2. Шлёте команды в TC2 через Broadlink RM. Меня интересует управление TC2 в отсутствии Broadlink RM. Каков протокол обучения TC2?
