### ISSUE TITLE
Speed for AirConditioner

### ISSUE THREAD

**Issue by cece99** [lprhodes/homebridge-broadlink-rm#174] opened 2017-08-05 22:22 UTC
I think that adding the possibility of regulating the speed of the air conditioner would be useful and appreciated. 
As far as I understood the speed setting is not supported natively by HomeKit, as a workaround I was thinking that a fan accessory could be created together with the AC accessory to set the speed.

**Comment by lprhodes** [comment] 2018-02-08 08:41
I like the idea of combining the two accessory types but the problem is that you'd end up needing so many variations of the IR codes

**Comment by lprhodes** [comment] 2018-02-28 00:07
Closing for now as it seems impractical to learn all of these codes. Happy to be persuaded otherwise.

**Closed by lprhodes** 2018-02-28 00:07 UTC
Labels: info requested
