### ISSUE TITLE
TV Switch

### ISSUE THREAD

**Issue by TooSpeedy** [lprhodes/homebridge-broadlink-rm#203] opened 2017-11-03 23:04 UTC
Is there a way to show the status of a device?

For example, the TV switch, if you turn on the Device, is there a way you can even ping the TV's ip address to see if it responds, if it does the Home app will show it as on, and if no response it says off?

Or any other potential method? I just don't want to turn the TV off with the remote and then in the app it says something different to the actual state of the TV.

**Comment by lprhodes** [comment] 2018-02-08 09:11
Dupe of #154

**Closed by lprhodes** 2018-02-08 09:11 UTC
