### ISSUE TITLE
Fan Speed

### ISSUE THREAD

**Issue by cquanu** [lprhodes/homebridge-broadlink-rm#223] opened 2017-12-28 06:46 UTC
I’ve a fan with 3 speeds. Low, Medium and High. But there’s a problem. When I adjust the speed to 25%(Low) then medium will go to 26% then 27% to high then back to 28% Low.

Is there a way to stop this behaviour by checking if the requested speed is close to the current speed then no IR signal will be sent. Example, current speed is at 25% then if requested speed is 26% don’t send any new IR signal since is closer to 25% which is already at low speed.

Here’s my config.
```
{
                    "name": "Fan",
                    "type": "fan",
                    "hideV1Fan": "true",
                    "data": {
                        "on": "26006c0070731b571b571b1e1b571b571b571b1e1b1e1b1e1c1d1c1e1b571b1e1b1e1b571b1e1b1e1c1e1a581b561c561c561a581b1e1c0005266f741c561b571b1e1c561b571b571b1e1c1d1c1e1b1e1a1f1b571b1e1b1e1b571b1e1b1f1b1e1b571b571a581b561c561c1e1b000d05000000000000000000000000",
                        "off": "26006c0070731b571b571b1e1b571b571b571b1e1b1e1b1e1c1d1c1e1b571b1e1b1e1b571b1e1b1e1c1e1a581b561c561c561a581b1e1c0005266f741c561b571b1e1c561b571b571b1e1c1d1c1e1b1e1a1f1b571b1e1b1e1b571b1e1b1f1b1e1b571b571a581b561c561c1e1b000d05000000000000000000000000",
                        "swingToggle": "26006c0070741b571b571b1e1b571a571b571c561c1e1b561c561b571b1f1b1e1a1f1b571b1e1a1f1b1f1b1e1b571b1e1b1e1b1e1b571c00052670731a581b571b1e1b571b561b581b561c1e1a571c561c561b1f1b1e1a1f1a581b1e1b1e1b1f1b1e1a581b1e1b1e1b1e1b571b000d05000000000000000000000000",
                        "fanSpeed25": "26006c0070731b571b571b1e1b571b571b571b1e1b1e1b1e1c1d1c1e1b571b1e1b1e1b571b1e1b1e1c1e1a581b561c561c561a581b1e1c0005266f741c561b571b1e1c561b571b571b1e1c1d1c1e1b1e1a1f1b571b1e1b1e1b571b1e1b1f1b1e1b571b571a581b561c561c1e1b000d02000000000000000000000000",
                        "fanSpeed50": "260036006f751b561c561c1e1b561b571a581b571a581a581a581a571b1f1a1f1a1f1c561a1f1b1f1b1e1b1e1a1f1b1f1a1f1a1f1a581b000d050000",
                        "fanSpeed100": "260036006f751b561c561c1e1b561b571a581b571a581a581a581a571b1f1a1f1a1f1c561a1f1b1f1b1e1b1e1a1f1b1f1a1f1a1f1a581b000d050000"
                    }
```

**Comment by lprhodes** [comment] 2018-02-09 01:22
That's not something I'm looking to implement at the moment, sorry.

You can make it work with what you have though:

Change "fanSpeed25" to "fanSpeed37"
Change "fanSpeed50" to "fanSpeed62"

**Comment by cquanu** [comment] 2018-02-09 12:30
Hi, actually I meant is it possible to make the fan speed 'snap' at specific percentage and only send code when at the percentage.

BTW. Thanks for the work and commitment ! I see a lot of releases today and should i update now because v2.5.16 is stable for me.

**Comment by lprhodes** [comment] 2018-02-09 12:35
Ah I see, I'll have a think on that one. I also just noticed you're wrapping quotes around true - make sure true/false use { example: true } rather than { example: "true" }

It's hard to tell - I've just fixed a couple of issues people have raised but there are a lot of options to consider. It's been stable for me though...and I'm around to fix things.

I'll be adding tests in the near future so that I can be more confident about it's stability.

**Comment by webdot** [comment] 2018-02-10 10:40
I got this error after i update.


/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:48
    if (showRotationDirection !== false) showRotationDirection = true
        ^

ReferenceError: showRotationDirection is not defined
    at FanAccessory.getServices (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:48:9)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:388:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:374:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:40:5)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by cquanu** [comment] 2018-02-10 14:37
Hi, how can i fix this?

/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:46
    if (showV2Fan !== false) showV2Fan = true
                                       ^

TypeError: Assignment to constant variable.
    at FanAccessory.getServices (/usr/local/lib/node_modules/homebridge-broadlin                               k-rm/accessories/fan.js:46:40)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/serve                               r.js:388:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:                               374:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/o                               nce.js:16:19
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-b                               roadlink-rm/node_modules/homebridge-platform-helper/platform.js:40:5)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/l                               ib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.                               js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge                               :17:22)

**Comment by lprhodes** [comment] 2018-02-11 22:11
Fixed in 2.6.4

**Comment by cquanu** [comment] 2018-03-14 00:31
Sry for bring this issue up again.. since v3 is here will we ever get a ‘snap fan speed’?

**Comment by lprhodes** [comment] 2018-03-14 00:34
Would it work well for you if the fan as to work like the light currently does?

**Comment by lprhodes** [comment] 2018-03-14 00:42
Forget that, it does work like the light does.

I'm still unsure what the issue is sorry!

The following config should allow for low, medium and high hex codes:

```
{
    "name": "Fan",
    "type": "fan",
    "data": {
        "on": "ON_HEX",
        "off": "OFF_HEX",
        "swingToggle": "SWING_HEX",
        "fanSpeed25": "LOW_HEX",
        "fanSpeed50": "MEDIUM_HEX",
        "fanSpeed75": "HIGH_HEX",
    }
}
```

Any speed from 1% to  36% will then send LOW_HEX
Any speed from 37% to 62% will then send MEDIUM_HEX
Any speed from 63% to 100% will then send HIGH_HEX

**Comment by cquanu** [comment] 2018-03-14 01:07
That’s what I did. But the hex code fired every time I adjust the slider regardless of %. Is it possible to not send the same hex code again if the fan speed is already on/within the selected current speed

**Comment by lprhodes** [comment] 2018-03-14 01:22
Got it - version 3.0.3 will prevent the same code from being sent multiple times.

**Closed by lprhodes** 2018-03-14 01:22 UTC
Labels: enhancement

**Comment by cquanu** [comment] 2018-03-14 01:25
That’s fast! Thank you very much!
