### ISSUE TITLE
GarageGateOpener init issues

### ISSUE THREAD

**Issue by wzpyh** [lprhodes/homebridge-broadlink-rm#163] opened 2017-07-21 05:26 UTC
I recently added a GarageGateOpener and debugging the code with my Homebridge-Mi-Platform ,and notice that sometimes method setTargetDoorState will be called when start running homebridge and the hexstring is open hex data.

that means if you restart your homebridge for some reason , your garage gate will be opened because of that ..

**Comment by iandronowicz** [comment] 2017-11-28 00:30
exactly same issue with window covering accessories: when Homebridge starts it closes some blinds and then the home app shows open but they are closed. Weird.

**Comment by sdtaheri** [comment] 2018-02-06 23:22
I have the same issue too

**Comment by lprhodes** [comment] 2018-02-08 14:05
Can you please provide logs and your config. I've been unable to reproduce this

**Comment by lprhodes** [comment] 2018-02-28 00:04
Closing, please re-open if you would still like help

**Closed by lprhodes** 2018-02-28 00:04 UTC
Labels: bug, info requested
